// Generated by gencpp from file direct_lidar_inertial_odometry/save_pcd.msg
// DO NOT EDIT!


#ifndef DIRECT_LIDAR_INERTIAL_ODOMETRY_MESSAGE_SAVE_PCD_H
#define DIRECT_LIDAR_INERTIAL_ODOMETRY_MESSAGE_SAVE_PCD_H

#include <ros/service_traits.h>


#include <direct_lidar_inertial_odometry/save_pcdRequest.h>
#include <direct_lidar_inertial_odometry/save_pcdResponse.h>


namespace direct_lidar_inertial_odometry
{

struct save_pcd
{

typedef save_pcdRequest Request;
typedef save_pcdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct save_pcd
} // namespace direct_lidar_inertial_odometry


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::direct_lidar_inertial_odometry::save_pcd > {
  static const char* value()
  {
    return "9fd870b6932171ca7a964d532d4402b9";
  }

  static const char* value(const ::direct_lidar_inertial_odometry::save_pcd&) { return value(); }
};

template<>
struct DataType< ::direct_lidar_inertial_odometry::save_pcd > {
  static const char* value()
  {
    return "direct_lidar_inertial_odometry/save_pcd";
  }

  static const char* value(const ::direct_lidar_inertial_odometry::save_pcd&) { return value(); }
};


// service_traits::MD5Sum< ::direct_lidar_inertial_odometry::save_pcdRequest> should match
// service_traits::MD5Sum< ::direct_lidar_inertial_odometry::save_pcd >
template<>
struct MD5Sum< ::direct_lidar_inertial_odometry::save_pcdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::direct_lidar_inertial_odometry::save_pcd >::value();
  }
  static const char* value(const ::direct_lidar_inertial_odometry::save_pcdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::direct_lidar_inertial_odometry::save_pcdRequest> should match
// service_traits::DataType< ::direct_lidar_inertial_odometry::save_pcd >
template<>
struct DataType< ::direct_lidar_inertial_odometry::save_pcdRequest>
{
  static const char* value()
  {
    return DataType< ::direct_lidar_inertial_odometry::save_pcd >::value();
  }
  static const char* value(const ::direct_lidar_inertial_odometry::save_pcdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::direct_lidar_inertial_odometry::save_pcdResponse> should match
// service_traits::MD5Sum< ::direct_lidar_inertial_odometry::save_pcd >
template<>
struct MD5Sum< ::direct_lidar_inertial_odometry::save_pcdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::direct_lidar_inertial_odometry::save_pcd >::value();
  }
  static const char* value(const ::direct_lidar_inertial_odometry::save_pcdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::direct_lidar_inertial_odometry::save_pcdResponse> should match
// service_traits::DataType< ::direct_lidar_inertial_odometry::save_pcd >
template<>
struct DataType< ::direct_lidar_inertial_odometry::save_pcdResponse>
{
  static const char* value()
  {
    return DataType< ::direct_lidar_inertial_odometry::save_pcd >::value();
  }
  static const char* value(const ::direct_lidar_inertial_odometry::save_pcdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DIRECT_LIDAR_INERTIAL_ODOMETRY_MESSAGE_SAVE_PCD_H
